title: VH Biomarker Reference Guide
description: Voloridge Health Biomarker Reference Guide
theme: just-the-docs
logo: "/assets/images/logo.png"
markdown: kramdown
callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red
url: https://rr.voloridge.health
assets:
  css:
    - /assets/css/custom.css
permalink: pretty
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

